x=25.3
y=30
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x*y+5)
print((x*y)+(y-x)/3)
print(str(x))
print(str(x)+"is my age")
print(abs(x))
print(pow(2,5))
print(max(3,5))
print(min(3,5))
print(round(x))
from math import *
print(floor(3.4))
print(ceil(3.4))
print(sqrt(25))