x="John is a Good Boy"
print("hello \n world!")
print("hello \"world!\"")
print(x+"and kindhearted")
print(x.lower())
print(x.upper())
print(x.islower())
print(x.isupper())
print(x.lower().islower())
print(x.upper().isupper())
print(len(x))
print(x[7])
print(x.index("Good"))
print(x.replace("Good","Cool"))